CREATE DATABASE shop;

CREATE TABLE CUSTOMER (
id int not null primary key,
name varchar(50) not null,
location varchar(50) not null,
male_female boolean,
birth_date date not null
);

CREATE TABLE DRUG (
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
COMPANY VARCHAR(50) NOT NULL,
PRICE INT NOT NULL,
MADE_IN_COUNTRY VARCHAR(100) NOT NULL
);

CREATE TABLE ROUTE (
ID INT NOT NULL PRIMARY KEY,
FROM_ VARCHAR(50) NOT NULL,
TO_ VARCHAR(50) NOT NULL,
TRANSPORT VARCHAR(50) NOT NULL,
HOURS INT NOT NULL
);

CREATE TABLE DELIVERY (
ID INT NOT NULL PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
DRUG_ID INT NOT NULL,
FOREIGN KEY (DRUG_ID) REFERENCES DRUG(ID),
ROUTE_ID INT NOT NULL,
FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ID),
PRODUCT_AMOUNT INT NOT NULL
);