SELECT NAME , BIRTH_DATE, (SELECT NAME FROM DRUG WHERE EXISTS(SELECT * FROM DELIVERY WHERE DRUG_ID = DRUG.ID AND CUSTOMER_ID = CUSTOMER.ID)) AS SQ
INTO DISCOUNT_CUSTOMERS
FROM CUSTOMER WHERE BIRTH_DATE <= '1960-01-01'::DATE