INSERT INTO DELIVERY (ID, CUSTOMER_ID, DRUG_ID, ROUTE_ID, PRODUCT_AMOUNT)
SELECT
	1001::INTEGER,
	(	SELECT MAX(ID) FROM CUSTOMER
		LIMIT 1
	),
	(
		SELECT ID 
		FROM DRUG
		WHERE  NAME LIKE '%Vitamin%'
		LIMIT 1
	),
	(	SELECT ID
		FROM ROUTE
		LIMIT 1
	),
	5::INTEGER
		