WITH CTE (NAME, PRICE, MADE_IN_COUNTRY) AS	
(
	SELECT NAME, PRICE, MADE_IN_COUNTRY
	FROM DRUG
	WHERE COMPANY LIKE '%Colgate%'
)
SELECT AVG (PRICE::NUMERIC) AS AVERAGE_PRICE_FOR_DRUG_OF_COLGATE
FROM CTE