DROP TABLE TMP_TAB;
SELECT *
INTO TMP_TAB
FROM DRUG
ORDER BY EXPIRATION_DATE;

WITH RECURSIVE FRESH_DRUGS  AS
(
	SELECT ID, NAME, EXPIRATION_DATE 
	FROM TMP_TAB
	WHERE EXPIRATION_DATE = (SELECT MIN(EXPIRATION_DATE) FROM TMP_TAB)
	UNION 
	SELECT ID, NAME, EXPIRATION_DATE
	FROM TMP_TAB
	WHERE EXPIRATION_DATE <= '2025-01-01'::DATE AND ID IN 	(	SELECT DRUG_ID 
																FROM DELIVERY
																WHERE ROUTE_ID IN 	(	SELECT ID 
																						FROM ROUTE
																						WHERE MED_FRIDGE = 1::BOOLEAN)
															)
					
)
SELECT ID, NAME, EXPIRATION_DATE
FROM FRESH_DRUGS