SELECT * FROM CUSTOMER WHERE EXISTS(
									 SELECT CUSTOMER_ID, DRUG_ID FROM DELIVERY
									WHERE (CUSTOMER.ID = DELIVERY.CUSTOMER_ID AND DRUG_ID IN (SELECT ID FROM DRUG WHERE DRUG.NAME = 'Ibuprofen')))