SELECT MADE_IN_COUNTRY, PRICE, EXPIRATION_DATE,
	(SELECT AVG(PRICE::NUMERIC) FROM DRUG WHERE MADE_IN_COUNTRY = 'Cuba') AS AVG_CUBA_PRICE,
	(SELECT MIN(EXPIRATION_DATE) FROM DRUG WHERE MADE_IN_COUNTRY = 'Cuba') AS MIN_DATE_DRUG_CUBA
	FROM DRUG

	