SELECT FROM_, TO_, 
	CASE 
		WHEN MED_FRIDGE = 1::BOOLEAN AND TRANSPORT_TYPE = 'air' THEN 'PLANE WITH FRIDGE'
		WHEN MED_FRIDGE = 0::BOOLEAN AND TRANSPORT_TYPE = 'air' THEN 'PLANE WITHOUT FRIDGE'
		ELSE 'NOT EVEN PLANE'
	END AIR_FRIDGE_CASE
	FROM ROUTE
	